#list of targets for star parties, these are considered static targets

from django.core.management.base import BaseCommand
from outreach.models import AstronomicalTarget

DEFAULT_TARGETS = [
    {'name': 'Orion Nebula',
 'target_type': 'DSO',
 'constellation': 'Orion',
 'ra_hours': 5.5881,
 'dec_degrees': -5.3911,
 'best_months': ['12', '1', '2', '3'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Bright stellar nursery where new stars are forming.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Running Man Nebula',
 'target_type': 'DSO',
 'constellation': 'Orion',
 'ra_hours': 5.5897,
 'dec_degrees': -4.8492,
 'best_months': ['12', '1', '2', '3'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Reflection nebula near the Orion Nebula.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Pleiades',
 'target_type': 'DSO',
 'constellation': 'Taurus',
 'ra_hours': 3.79,
 'dec_degrees': 24.1167,
 'best_months': ['11', '12', '1', '2', '3'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Open star cluster also called the Seven Sisters.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Hyades',
 'target_type': 'DSO',
 'constellation': 'Taurus',
 'ra_hours': 4.45,
 'dec_degrees': 15.8667,
 'best_months': ['11', '12', '1', '2', '3'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Large nearby open cluster forming the face of Taurus.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Double Cluster',
 'target_type': 'DSO',
 'constellation': 'Perseus',
 'ra_hours': 2.3333,
 'dec_degrees': 57.1333,
 'best_months': ['10', '11', '12', '1', '2'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Two neighboring open clusters rich with young stars.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'M35',
 'target_type': 'DSO',
 'constellation': 'Gemini',
 'ra_hours': 6.15,
 'dec_degrees': 24.3333,
 'best_months': ['12', '1', '2', '3', '4'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Bright open cluster in Gemini.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'M36',
 'target_type': 'DSO',
 'constellation': 'Auriga',
 'ra_hours': 5.6067,
 'dec_degrees': 34.14,
 'best_months': ['12', '1', '2', '3'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Compact open cluster in Auriga.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'M37',
 'target_type': 'DSO',
 'constellation': 'Auriga',
 'ra_hours': 5.8722,
 'dec_degrees': 32.5533,
 'best_months': ['12', '1', '2', '3'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Rich open cluster with many faint stars.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'M38',
 'target_type': 'DSO',
 'constellation': 'Auriga',
 'ra_hours': 5.4783,
 'dec_degrees': 35.855,
 'best_months': ['12', '1', '2', '3'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Open cluster sometimes described as cross-shaped.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Beehive Cluster',
 'target_type': 'DSO',
 'constellation': 'Cancer',
 'ra_hours': 8.6667,
 'dec_degrees': 19.6667,
 'best_months': ['1', '2', '3', '4', '5'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Large open cluster visible in binoculars and small telescopes.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'M67',
 'target_type': 'DSO',
 'constellation': 'Cancer',
 'ra_hours': 8.8561,
 'dec_degrees': 11.8125,
 'best_months': ['2', '3', '4', '5'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Old open cluster with Sun-like stars.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Eskimo Nebula',
 'target_type': 'DSO',
 'constellation': 'Gemini',
 'ra_hours': 7.4852,
 'dec_degrees': 20.9118,
 'best_months': ['1', '2', '3', '4'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Planetary nebula useful for discussing the late life of stars.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Sirius',
 'target_type': 'OTHER',
 'constellation': 'Canis Major',
 'ra_hours': 6.7525,
 'dec_degrees': -16.7161,
 'best_months': ['12', '1', '2', '3'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Brightest star in the night sky.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Betelgeuse',
 'target_type': 'OTHER',
 'constellation': 'Orion',
 'ra_hours': 5.9195,
 'dec_degrees': 7.4071,
 'best_months': ['12', '1', '2', '3'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Red supergiant star in Orion.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Rigel',
 'target_type': 'OTHER',
 'constellation': 'Orion',
 'ra_hours': 5.2423,
 'dec_degrees': -8.2016,
 'best_months': ['12', '1', '2', '3'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Blue-white supergiant star in Orion.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Aldebaran',
 'target_type': 'OTHER',
 'constellation': 'Taurus',
 'ra_hours': 4.5987,
 'dec_degrees': 16.5093,
 'best_months': ['11', '12', '1', '2', '3'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Orange giant star marking the eye of Taurus.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Capella',
 'target_type': 'OTHER',
 'constellation': 'Auriga',
 'ra_hours': 5.2782,
 'dec_degrees': 45.998,
 'best_months': ['11', '12', '1', '2', '3'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Bright star in Auriga, good for winter sky orientation.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Orion',
 'target_type': 'CONSTELLATION',
 'constellation': 'Orion',
 'ra_hours': 5.5,
 'dec_degrees': -1.0,
 'best_months': ['12', '1', '2', '3'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'One of the easiest constellations for the public to recognize.',
 'representative_point': 'Representative constellation center near Orion Belt/M42'},
    {'name': 'Taurus',
 'target_type': 'CONSTELLATION',
 'constellation': 'Taurus',
 'ra_hours': 4.6,
 'dec_degrees': 16.5,
 'best_months': ['11', '12', '1', '2', '3'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Contains Aldebaran, the Hyades, and the Pleiades.',
 'representative_point': 'Representative constellation center near Aldebaran/Hyades'},
    {'name': 'Winter Hexagon',
 'target_type': 'CONSTELLATION',
 'constellation': '',
 'ra_hours': 6.3,
 'dec_degrees': 15.0,
 'best_months': ['12', '1', '2', '3'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Large winter asterism connecting several bright stars.',
 'representative_point': 'Representative asterism center'},
    {'name': 'Leo Triplet',
 'target_type': 'DSO',
 'constellation': 'Leo',
 'ra_hours': 11.3167,
 'dec_degrees': 13.25,
 'best_months': ['3', '4', '5'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Group of three galaxies; best under darker skies.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'M3',
 'target_type': 'DSO',
 'constellation': 'Canes Venatici',
 'ra_hours': 13.7037,
 'dec_degrees': 28.3773,
 'best_months': ['3', '4', '5', '6'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Bright globular cluster of ancient stars.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'M53',
 'target_type': 'DSO',
 'constellation': 'Coma Berenices',
 'ra_hours': 13.2153,
 'dec_degrees': 18.1682,
 'best_months': ['3', '4', '5', '6'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Globular cluster useful for discussing old star populations.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Coma Star Cluster',
 'target_type': 'DSO',
 'constellation': 'Coma Berenices',
 'ra_hours': 12.4,
 'dec_degrees': 26.0,
 'best_months': ['3', '4', '5', '6'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Large loose star cluster visible in binoculars.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Sombrero Galaxy',
 'target_type': 'DSO',
 'constellation': 'Virgo',
 'ra_hours': 12.6665,
 'dec_degrees': -11.6231,
 'best_months': ['3', '4', '5', '6'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Galaxy with a prominent dark dust lane.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': "M81 Bode's Galaxy",
 'target_type': 'DSO',
 'constellation': 'Ursa Major',
 'ra_hours': 9.9259,
 'dec_degrees': 69.0653,
 'best_months': ['2', '3', '4', '5'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Bright spiral galaxy in Ursa Major.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'M82 Cigar Galaxy',
 'target_type': 'DSO',
 'constellation': 'Ursa Major',
 'ra_hours': 9.9319,
 'dec_degrees': 69.6797,
 'best_months': ['2', '3', '4', '5'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Starburst galaxy near M81.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'M51 Whirlpool Galaxy',
 'target_type': 'DSO',
 'constellation': 'Canes Venatici',
 'ra_hours': 13.4979,
 'dec_degrees': 47.1953,
 'best_months': ['3', '4', '5', '6'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Interacting galaxy pair; best under darker skies.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Big Dipper',
 'target_type': 'CONSTELLATION',
 'constellation': 'Ursa Major',
 'ra_hours': 11.3,
 'dec_degrees': 56.0,
 'best_months': ['3', '4', '5', '6', '7'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Useful for finding Polaris and explaining circumpolar stars.',
 'representative_point': 'Representative asterism center near the bowl'},
    {'name': 'Polaris',
 'target_type': 'OTHER',
 'constellation': 'Ursa Minor',
 'ra_hours': 2.5303,
 'dec_degrees': 89.2641,
 'best_months': [],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'North Star; useful for explaining Earth’s rotation and navigation.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Arcturus',
 'target_type': 'OTHER',
 'constellation': 'Boötes',
 'ra_hours': 14.261,
 'dec_degrees': 19.1824,
 'best_months': ['3', '4', '5', '6', '7'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Bright orange giant star; found by arcing from the Big Dipper.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Cor Caroli',
 'target_type': 'OTHER',
 'constellation': 'Canes Venatici',
 'ra_hours': 12.9338,
 'dec_degrees': 38.3184,
 'best_months': ['3', '4', '5', '6'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Pretty double star; good for small telescopes.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Leo',
 'target_type': 'CONSTELLATION',
 'constellation': 'Leo',
 'ra_hours': 10.5,
 'dec_degrees': 15.0,
 'best_months': ['3', '4', '5'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Spring constellation shaped like a lion.',
 'representative_point': 'Representative constellation center near the Sickle/Regulus'},
    {'name': 'Virgo',
 'target_type': 'CONSTELLATION',
 'constellation': 'Virgo',
 'ra_hours': 13.4,
 'dec_degrees': -5.0,
 'best_months': ['4', '5', '6'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Region rich with galaxies.',
 'representative_point': 'Representative constellation center near Spica/Virgo region'},
    {'name': 'Boötes',
 'target_type': 'CONSTELLATION',
 'constellation': 'Boötes',
 'ra_hours': 14.261,
 'dec_degrees': 19.18,
 'best_months': ['4', '5', '6', '7'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Contains bright Arcturus.',
 'representative_point': 'Representative point: Arcturus'},
    {'name': 'M13 Hercules Cluster',
 'target_type': 'DSO',
 'constellation': 'Hercules',
 'ra_hours': 16.6951,
 'dec_degrees': 36.4613,
 'best_months': ['5', '6', '7', '8', '9'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Bright globular cluster with hundreds of thousands of stars.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'M92',
 'target_type': 'DSO',
 'constellation': 'Hercules',
 'ra_hours': 17.2854,
 'dec_degrees': 43.1359,
 'best_months': ['5', '6', '7', '8', '9'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Globular cluster often overshadowed by M13 but still excellent.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Ring Nebula',
 'target_type': 'DSO',
 'constellation': 'Lyra',
 'ra_hours': 18.8931,
 'dec_degrees': 33.0292,
 'best_months': ['6', '7', '8', '9', '10'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Planetary nebula formed by a dying star shedding outer layers.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Dumbbell Nebula',
 'target_type': 'DSO',
 'constellation': 'Vulpecula',
 'ra_hours': 19.9934,
 'dec_degrees': 22.721,
 'best_months': ['6', '7', '8', '9', '10'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Large planetary nebula; good for discussing stellar death.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Wild Duck Cluster',
 'target_type': 'DSO',
 'constellation': 'Scutum',
 'ra_hours': 18.8512,
 'dec_degrees': -6.27,
 'best_months': ['6', '7', '8', '9'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Rich open cluster near the Milky Way.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Lagoon Nebula',
 'target_type': 'DSO',
 'constellation': 'Sagittarius',
 'ra_hours': 18.0617,
 'dec_degrees': -24.3833,
 'best_months': ['6', '7', '8', '9'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Bright emission nebula and star-forming region.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Trifid Nebula',
 'target_type': 'DSO',
 'constellation': 'Sagittarius',
 'ra_hours': 18.045,
 'dec_degrees': -23.03,
 'best_months': ['6', '7', '8', '9'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Nebula with dark lanes dividing glowing gas.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Eagle Nebula',
 'target_type': 'DSO',
 'constellation': 'Serpens',
 'ra_hours': 18.3133,
 'dec_degrees': -13.8067,
 'best_months': ['6', '7', '8', '9'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Home of the famous Pillars of Creation.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Omega Nebula',
 'target_type': 'DSO',
 'constellation': 'Sagittarius',
 'ra_hours': 18.3464,
 'dec_degrees': -16.1767,
 'best_months': ['6', '7', '8', '9'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Bright star-forming nebula also known as the Swan Nebula.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'North America Nebula',
 'target_type': 'DSO',
 'constellation': 'Cygnus',
 'ra_hours': 20.9667,
 'dec_degrees': 44.3333,
 'best_months': ['6', '7', '8', '9', '10'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Large nebula; often better as a discussion or imaging target.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Veil Nebula',
 'target_type': 'DSO',
 'constellation': 'Cygnus',
 'ra_hours': 20.8333,
 'dec_degrees': 30.7167,
 'best_months': ['6', '7', '8', '9', '10'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Supernova remnant; best with dark skies and filters.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Coathanger Asterism',
 'target_type': 'OTHER',
 'constellation': 'Vulpecula',
 'ra_hours': 19.4167,
 'dec_degrees': 20.1833,
 'best_months': ['6', '7', '8', '9'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Fun binocular object shaped like a coat hanger.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Albireo',
 'target_type': 'OTHER',
 'constellation': 'Cygnus',
 'ra_hours': 19.512,
 'dec_degrees': 27.9597,
 'best_months': ['6', '7', '8', '9', '10'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Colorful double star often described as blue and gold.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Epsilon Lyrae',
 'target_type': 'OTHER',
 'constellation': 'Lyra',
 'ra_hours': 18.7397,
 'dec_degrees': 39.67,
 'best_months': ['6', '7', '8', '9', '10'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'The famous Double Double star near Vega.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Summer Triangle',
 'target_type': 'CONSTELLATION',
 'constellation': '',
 'ra_hours': 19.71,
 'dec_degrees': 31.0,
 'best_months': ['6', '7', '8', '9'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Seasonal guide formed by Vega, Deneb, and Altair.',
 'representative_point': 'Representative asterism center of Vega-Deneb-Altair'},
    {'name': 'Sagittarius Teapot',
 'target_type': 'CONSTELLATION',
 'constellation': 'Sagittarius',
 'ra_hours': 18.35,
 'dec_degrees': -28.0,
 'best_months': ['6', '7', '8', '9'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Points toward the center of the Milky Way.',
 'representative_point': 'Representative asterism center of the Teapot'},
    {'name': 'Cygnus',
 'target_type': 'CONSTELLATION',
 'constellation': 'Cygnus',
 'ra_hours': 20.3,
 'dec_degrees': 40.0,
 'best_months': ['6', '7', '8', '9', '10'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'The Swan; rich Milky Way constellation.',
 'representative_point': 'Representative constellation center in Cygnus'},
    {'name': 'Lyra',
 'target_type': 'CONSTELLATION',
 'constellation': 'Lyra',
 'ra_hours': 18.616,
 'dec_degrees': 38.78,
 'best_months': ['6', '7', '8', '9', '10'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Small constellation containing Vega and the Ring Nebula.',
 'representative_point': 'Representative point: Vega'},
    {'name': 'Scorpius',
 'target_type': 'CONSTELLATION',
 'constellation': 'Scorpius',
 'ra_hours': 16.49,
 'dec_degrees': -26.43,
 'best_months': ['5', '6', '7', '8'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Bright summer constellation with a distinctive curved tail.',
 'representative_point': 'Representative point: Antares'},
    {'name': 'Antares',
 'target_type': 'OTHER',
 'constellation': 'Scorpius',
 'ra_hours': 16.4901,
 'dec_degrees': -26.4319,
 'best_months': ['5', '6', '7', '8'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Red supergiant star and heart of Scorpius.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Andromeda Galaxy',
 'target_type': 'DSO',
 'constellation': 'Andromeda',
 'ra_hours': 0.7123,
 'dec_degrees': 41.2692,
 'best_months': ['9', '10', '11', '12'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Nearest large galaxy to the Milky Way.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'M15',
 'target_type': 'DSO',
 'constellation': 'Pegasus',
 'ra_hours': 21.5006,
 'dec_degrees': 12.167,
 'best_months': ['8', '9', '10', '11'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Dense globular cluster in Pegasus.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'M2',
 'target_type': 'DSO',
 'constellation': 'Aquarius',
 'ra_hours': 21.5575,
 'dec_degrees': -0.8233,
 'best_months': ['8', '9', '10', '11'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Large globular cluster visible in fall skies.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'ET Cluster',
 'target_type': 'DSO',
 'constellation': 'Cassiopeia',
 'ra_hours': 1.33,
 'dec_degrees': 58.29,
 'best_months': ['9', '10', '11', '12', '1'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Open cluster whose stars resemble a little figure with raised arms.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Owl Cluster',
 'target_type': 'DSO',
 'constellation': 'Cassiopeia',
 'ra_hours': 1.33,
 'dec_degrees': 58.29,
 'best_months': ['9', '10', '11', '12', '1'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Open cluster also known as the Dragonfly Cluster.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'M34',
 'target_type': 'DSO',
 'constellation': 'Perseus',
 'ra_hours': 2.7033,
 'dec_degrees': 42.7467,
 'best_months': ['9', '10', '11', '12'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Open cluster in Perseus.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'M52',
 'target_type': 'DSO',
 'constellation': 'Cassiopeia',
 'ra_hours': 23.4145,
 'dec_degrees': 61.5933,
 'best_months': ['9', '10', '11', '12'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Compact open cluster near Cassiopeia.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': "NGC 7789 Caroline's Rose",
 'target_type': 'DSO',
 'constellation': 'Cassiopeia',
 'ra_hours': 23.96,
 'dec_degrees': 56.724,
 'best_months': ['9', '10', '11', '12'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Rich open cluster discovered by Caroline Herschel.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Mirach',
 'target_type': 'OTHER',
 'constellation': 'Andromeda',
 'ra_hours': 1.1622,
 'dec_degrees': 35.6206,
 'best_months': ['9', '10', '11', '12'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Bright star useful for finding the Andromeda Galaxy.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Almach',
 'target_type': 'OTHER',
 'constellation': 'Andromeda',
 'ra_hours': 2.0649,
 'dec_degrees': 42.3297,
 'best_months': ['9', '10', '11', '12'],
 'visible_during_event': True,
 'discussion_only': False,
 'outreach_notes': 'Beautiful colored double star.',
 'representative_point': 'Catalog/object coordinates'},
    {'name': 'Pegasus Square',
 'target_type': 'CONSTELLATION',
 'constellation': 'Pegasus',
 'ra_hours': 23.55,
 'dec_degrees': 21.0,
 'best_months': ['9', '10', '11'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Useful fall asterism for star-hopping.',
 'representative_point': 'Representative asterism center of the Great Square'},
    {'name': 'Cassiopeia W',
 'target_type': 'CONSTELLATION',
 'constellation': 'Cassiopeia',
 'ra_hours': 0.68,
 'dec_degrees': 56.5,
 'best_months': ['9', '10', '11', '12', '1'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Easy-to-recognize W-shaped constellation.',
 'representative_point': 'Representative constellation point near Schedar'},
    {'name': 'Perseus',
 'target_type': 'CONSTELLATION',
 'constellation': 'Perseus',
 'ra_hours': 3.405,
 'dec_degrees': 49.86,
 'best_months': ['10', '11', '12', '1'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Fall and winter constellation rich with clusters.',
 'representative_point': 'Representative point: Mirfak'},
    {'name': 'Andromeda',
 'target_type': 'CONSTELLATION',
 'constellation': 'Andromeda',
 'ra_hours': 1.162,
 'dec_degrees': 35.62,
 'best_months': ['9', '10', '11', '12'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Home region of the Andromeda Galaxy.',
 'representative_point': 'Representative point: Mirach'},
    {'name': 'Aquarius',
 'target_type': 'CONSTELLATION',
 'constellation': 'Aquarius',
 'ra_hours': 22.2,
 'dec_degrees': -10.0,
 'best_months': ['8', '9', '10', '11'],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Large zodiac constellation in the fall sky.',
 'representative_point': 'Representative constellation center in Aquarius'},
    {'name': 'Quadrantid Meteor Shower',
 'target_type': 'METEOR_SHOWER',
 'constellation': 'Boötes',
 'ra_hours': 15.3,
 'dec_degrees': 49.0,
 'best_months': ['1'],
 'visible_during_event': False,
 'discussion_only': True,
 'outreach_notes': 'Annual meteor shower peaking in early January.',
 'representative_point': 'Meteor shower radiant'},
    {'name': 'Lyrid Meteor Shower',
 'target_type': 'METEOR_SHOWER',
 'constellation': 'Lyra',
 'ra_hours': 18.1,
 'dec_degrees': 34.0,
 'best_months': ['4'],
 'visible_during_event': False,
 'discussion_only': True,
 'outreach_notes': 'Annual April meteor shower.',
 'representative_point': 'Meteor shower radiant'},
    {'name': 'Eta Aquariid Meteor Shower',
 'target_type': 'METEOR_SHOWER',
 'constellation': 'Aquarius',
 'ra_hours': 22.5,
 'dec_degrees': -1.0,
 'best_months': ['5'],
 'visible_during_event': False,
 'discussion_only': True,
 'outreach_notes': "Meteor shower associated with debris from Halley's Comet.",
 'representative_point': 'Meteor shower radiant'},
    {'name': 'Southern Delta Aquariid Meteor Shower',
 'target_type': 'METEOR_SHOWER',
 'constellation': 'Aquarius',
 'ra_hours': 22.7,
 'dec_degrees': -16.0,
 'best_months': ['7', '8'],
 'visible_during_event': False,
 'discussion_only': True,
 'outreach_notes': 'Summer meteor shower best seen from darker skies.',
 'representative_point': 'Meteor shower radiant'},
    {'name': 'Perseid Meteor Shower',
 'target_type': 'METEOR_SHOWER',
 'constellation': 'Perseus',
 'ra_hours': 3.1,
 'dec_degrees': 58.0,
 'best_months': ['8'],
 'visible_during_event': False,
 'discussion_only': True,
 'outreach_notes': 'Popular annual meteor shower peaking in August.',
 'representative_point': 'Meteor shower radiant'},
    {'name': 'Orionid Meteor Shower',
 'target_type': 'METEOR_SHOWER',
 'constellation': 'Orion',
 'ra_hours': 6.3,
 'dec_degrees': 16.0,
 'best_months': ['10'],
 'visible_during_event': False,
 'discussion_only': True,
 'outreach_notes': "Meteor shower associated with debris from Halley's Comet.",
 'representative_point': 'Meteor shower radiant'},
    {'name': 'Leonid Meteor Shower',
 'target_type': 'METEOR_SHOWER',
 'constellation': 'Leo',
 'ra_hours': 10.2,
 'dec_degrees': 22.0,
 'best_months': ['11'],
 'visible_during_event': False,
 'discussion_only': True,
 'outreach_notes': 'Annual meteor shower famous for occasional meteor storms.',
 'representative_point': 'Meteor shower radiant'},
    {'name': 'Geminid Meteor Shower',
 'target_type': 'METEOR_SHOWER',
 'constellation': 'Gemini',
 'ra_hours': 7.5,
 'dec_degrees': 32.0,
 'best_months': ['12'],
 'visible_during_event': False,
 'discussion_only': True,
 'outreach_notes': 'Strong annual meteor shower peaking in December.',
 'representative_point': 'Meteor shower radiant'},
    {'name': 'Light Pollution',
 'target_type': 'OTHER',
 'constellation': '',
 'ra_hours': None,
 'dec_degrees': None,
 'best_months': [],
 'visible_during_event': False,
 'discussion_only': True,
 'outreach_notes': 'Good discussion topic for sky brightness, dark skies, and responsible '
                   'lighting.',
 'representative_point': ''},
    {'name': 'Milky Way Structure',
 'target_type': 'OTHER',
 'constellation': '',
 'ra_hours': None,
 'dec_degrees': None,
 'best_months': ['6', '7', '8', '9'],
 'visible_during_event': False,
 'discussion_only': True,
 'outreach_notes': 'Explains our place inside a spiral galaxy.',
 'representative_point': ''},
    {'name': 'Scale of the Universe',
 'target_type': 'OTHER',
 'constellation': '',
 'ra_hours': None,
 'dec_degrees': None,
 'best_months': [],
 'visible_during_event': False,
 'discussion_only': True,
 'outreach_notes': 'Useful for explaining distances, light-years, and cosmic scale.',
 'representative_point': ''},
    {'name': 'Why Stars Twinkle',
 'target_type': 'OTHER',
 'constellation': '',
 'ra_hours': None,
 'dec_degrees': None,
 'best_months': [],
 'visible_during_event': False,
 'discussion_only': True,
 'outreach_notes': "Explains how Earth's atmosphere distorts starlight.",
 'representative_point': ''},
    {'name': 'Stellar Evolution',
 'target_type': 'OTHER',
 'constellation': '',
 'ra_hours': None,
 'dec_degrees': None,
 'best_months': [],
 'visible_during_event': False,
 'discussion_only': True,
 'outreach_notes': 'Connects nebulae, star clusters, red giants, and white dwarfs.',
 'representative_point': ''},
    {'name': 'Black Holes',
 'target_type': 'OTHER',
 'constellation': '',
 'ra_hours': None,
 'dec_degrees': None,
 'best_months': [],
 'visible_during_event': False,
 'discussion_only': True,
 'outreach_notes': 'Popular public topic for gravity, compact objects, and galaxies.',
 'representative_point': ''},
    {'name': 'Exoplanets',
 'target_type': 'OTHER',
 'constellation': '',
 'ra_hours': None,
 'dec_degrees': None,
 'best_months': [],
 'visible_during_event': False,
 'discussion_only': True,
 'outreach_notes': 'Good public topic for planets around other stars.',
 'representative_point': ''},
    {'name': 'How Telescopes Work',
 'target_type': 'OTHER',
 'constellation': '',
 'ra_hours': None,
 'dec_degrees': None,
 'best_months': [],
 'visible_during_event': False,
 'discussion_only': True,
 'outreach_notes': 'Explains mirrors, lenses, aperture, and magnification.',
 'representative_point': ''},
    {'name': 'Why Pluto Is a Dwarf Planet',
 'target_type': 'OTHER',
 'constellation': '',
 'ra_hours': None,
 'dec_degrees': None,
 'best_months': [],
 'visible_during_event': False,
 'discussion_only': True,
 'outreach_notes': 'Good conversation starter about how science classifies objects.',
 'representative_point': ''},
    {'name': 'How We Find North',
 'target_type': 'OTHER',
 'constellation': '',
 'ra_hours': None,
 'dec_degrees': None,
 'best_months': [],
 'visible_during_event': False,
 'discussion_only': True,
 'outreach_notes': "Uses Polaris, circumpolar stars, and Earth's rotation.",
 'representative_point': ''},
    {'name': 'Moon Phases',
 'target_type': 'MOON',
 'constellation': '',
 'ra_hours': None,
 'dec_degrees': None,
 'best_months': [],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Explains why the Moon changes shape through the month.',
 'representative_point': 'Dynamic Moon position'},
    {'name': 'Craters and Maria',
 'target_type': 'MOON',
 'constellation': '',
 'ra_hours': None,
 'dec_degrees': None,
 'best_months': [],
 'visible_during_event': True,
 'discussion_only': True,
 'outreach_notes': 'Good topic when the Moon is visible.',
 'representative_point': 'Dynamic Moon position'},
]


class Command(BaseCommand):
    help = "Seed default astronomical outreach targets."

    def handle(self, *args, **options):
        created_count = 0
        updated_count = 0

        for target_data in DEFAULT_TARGETS:
            target, created = AstronomicalTarget.objects.update_or_create(
                name=target_data["name"],
                defaults=target_data,
            )

            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Seed complete. Created: {created_count}. Updated: {updated_count}."
            )
        )