# Generated by Django 6.0.5 on 2026-06-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=200)),
                ('priority', models.IntegerField(default=3)),
                ('events_per_year', models.IntegerField(default=1)),
                ('allowed_weekdays', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
