# Generated by Django 6.0.5 on 2026-06-02 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='preferred_months',
            field=models.CharField(blank=True, help_text='Example: Jan,Feb,Mar or Oct-Apr', max_length=100),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timezone', models.CharField(default='America/Chicago', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='outreach.partner')),
            ],
        ),
    ]
