# Generated by Django 6.0.5 on 2026-06-02 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0005_scheduledevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('HOST', 'Host'), ('TELESCOPE', 'Telescope Operator'), ('WELCOME', 'Welcome Table'), ('ZOO', 'Telescope Petting Zoo'), ('DISPLAY', 'Display Setup'), ('OTHER', 'Other')], default='TELESCOPE', max_length=20)),
                ('equipment_brought', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_volunteers', to='outreach.scheduledevent')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to='outreach.volunteer')),
            ],
        ),
    ]
