# Generated by Django 6.0.5 on 2026-06-02 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0006_eventvolunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_start_time', models.TimeField(blank=True, null=True)),
                ('actual_end_time', models.TimeField(blank=True, null=True)),
                ('attendance', models.IntegerField(blank=True, null=True)),
                ('weather_conditions', models.CharField(blank=True, max_length=200)),
                ('sky_conditions', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('follow_up_needed', models.TextField(blank=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_log', to='outreach.scheduledevent')),
            ],
        ),
    ]
