# Generated by Django 6.0.5 on 2026-06-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0007_eventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvolunteer',
            name='equipment_notes',
            field=models.TextField(blank=True, help_text='Any extra equipment details or one-off items.'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='equipment_owned',
            field=models.TextField(blank=True, help_text='List equipment this volunteer owns, one item per line.'),
        ),
        migrations.AlterField(
            model_name='eventvolunteer',
            name='equipment_brought',
            field=models.TextField(blank=True, help_text='List equipment actually brought to this event.'),
        ),
    ]
