# Generated by Django 6.0.5 on 2026-06-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0008_eventvolunteer_equipment_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledevent',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20),
        ),
    ]
