# Generated by Django 6.0.5 on 2026-06-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0009_alter_scheduledevent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledevent',
            name='custom_event_title',
            field=models.CharField(blank=True, help_text='Only use this if Event title type is Custom.', max_length=100),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='event_title_type',
            field=models.CharField(choices=[('STAR_PARTY', 'Star Party'), ('SOLAR_OUTREACH', 'Solar Outreach'), ('LIBRARY_PROGRAM', 'Library Program'), ('SIDEWALK_ASTRONOMY', 'Sidewalk Astronomy'), ('CUSTOM', 'Custom')], default='STAR_PARTY', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='event_name',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
