# Generated by Django 6.0.5 on 2026-06-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0010_scheduledevent_custom_event_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledevent',
            name='date_confirmed',
            field=models.BooleanField(default=False, help_text='Check this once the partner has confirmed the date.'),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='partner_confirmed',
            field=models.BooleanField(default=False, help_text='Check this once the partner has confirmed participation.'),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='volunteers_confirmed',
            field=models.BooleanField(default=False, help_text='Check this once enough volunteers are confirmed.'),
        ),
    ]
