# Generated by Django 6.0.5 on 2026-06-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0011_scheduledevent_date_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledevent',
            name='partner_confirmed',
        ),
        migrations.RemoveField(
            model_name='scheduledevent',
            name='volunteers_confirmed',
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='host_assigned',
            field=models.BooleanField(default=False, help_text='Check this once an event host has been assigned.'),
        ),
    ]
