# Generated by Django 6.0.5 on 2026-06-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0012_remove_scheduledevent_partner_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledevent',
            name='date_confirmed',
            field=models.BooleanField(default=False, help_text='Check this once the event date has been confirmed.'),
        ),
    ]
