# Generated by Django 6.0.5 on 2026-06-08 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0013_alter_scheduledevent_date_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledevent',
            name='host_assigned',
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='host',
            field=models.ForeignKey(blank=True, help_text='Select the trained volunteer hosting this event.', limit_choices_to={'active': True, 'host_trained': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_events', to='outreach.volunteer'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='cleared_by_pfsp',
            field=models.BooleanField(default=False, help_text='Check if this volunteer is cleared by PFSP.'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='host_trained',
            field=models.BooleanField(default=False, help_text='Check if this volunteer is trained to host events.'),
        ),
    ]
