# Generated by Django 6.0.5 on 2026-06-08 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0014_remove_scheduledevent_host_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledevent',
            name='manual_host_name',
            field=models.CharField(blank=True, help_text='Use this for private parties or events hosted by someone not in the volunteer list.', max_length=200),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='host',
            field=models.ForeignKey(blank=True, help_text='Select the trained AAS host, if applicable.', limit_choices_to={'active': True, 'host_trained': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_events', to='outreach.volunteer'),
        ),
    ]
