# Generated by Django 6.0.5 on 2026-06-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0015_scheduledevent_manual_host_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventvolunteer',
            name='equipment_brought',
        ),
        migrations.RemoveField(
            model_name='eventvolunteer',
            name='equipment_notes',
        ),
    ]
