# Generated by Django 6.0.5 on 2026-06-08 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0016_remove_eventvolunteer_equipment_brought_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstronomicalTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('target_type', models.CharField(choices=[('PLANET', 'Planet'), ('METEOR_SHOWER', 'Meteor Shower'), ('DSO', 'Deep Sky Object'), ('COMET', 'Comet'), ('ECLIPSE', 'Eclipse'), ('CONSTELLATION', 'Constellation'), ('MOON', 'Moon'), ('OTHER', 'Other')], max_length=30)),
                ('constellation', models.CharField(blank=True, max_length=100)),
                ('best_months', models.CharField(blank=True, help_text='Example: Jan-Mar, Summer, Year Round', max_length=100)),
                ('visible_during_event', models.BooleanField(default=True, help_text='Check if this is usually something to observe, not just discuss.')),
                ('discussion_only', models.BooleanField(default=False, help_text='Check if this is mainly an interesting talking point.')),
                ('outreach_notes', models.TextField(blank=True, help_text='Public-friendly notes or talking points.')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='civil_dusk_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='moon_illumination',
            field=models.FloatField(blank=True, help_text='Moon illumination percentage.', null=True),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='moon_phase',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='nautical_dusk_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='suggested_laser_tour_time',
            field=models.TimeField(blank=True, help_text='Suggested laser constellation tour start time.', null=True),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='suggested_talk_start_time',
            field=models.TimeField(blank=True, help_text='Suggested 30-minute talk start time.', null=True),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='sunset_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_observe_during_event', models.BooleanField(default=True)),
                ('good_talking_point', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_targets', to='outreach.scheduledevent')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_appearances', to='outreach.astronomicaltarget')),
            ],
        ),
    ]
