# Generated by Django 6.0.5 on 2026-06-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0017_astronomicaltarget_scheduledevent_civil_dusk_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='scheduledevent',
            name='location',
        ),
        migrations.AddField(
            model_name='partner',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_role_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='partner',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='location_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='partner',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Use negative longitude for North America, example: -97.7431', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('YEARLY', 'Yearly Partner'), ('AD_HOC', 'Ad Hoc Event Requestor')], default='YEARLY', max_length=20),
        ),
        migrations.AddField(
            model_name='partner',
            name='preferred_contact_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='partner',
            name='scheduling_type',
            field=models.CharField(choices=[('DARKEST', 'Darkest Moon'), ('FIRST_FRIDAY', 'First Friday'), ('SPRING_FALL', 'Spring/Fall'), ('CUSTOM', 'Custom Rule')], default='DARKEST', max_length=30),
        ),
        migrations.AddField(
            model_name='partner',
            name='timezone',
            field=models.CharField(default='America/Chicago', max_length=100),
        ),
        migrations.AlterField(
            model_name='partner',
            name='allowed_weekdays',
            field=models.CharField(blank=True, help_text='Example: Friday, Saturday, Friday;Saturday', max_length=100),
        ),
        migrations.AlterField(
            model_name='partner',
            name='event_type',
            field=models.CharField(blank=True, help_text='Example: deep_sky, lunar, solar, general', max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='preferred_months',
            field=models.CharField(blank=True, help_text='Example: Oct-Apr, Spring/Fall, Year Round', max_length=100),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
