# Generated by Django 6.0.5 on 2026-06-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0018_remove_location_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='maximum_event_duration_minutes',
            field=models.IntegerField(blank=True, help_text='Maximum event duration in minutes. Example: 180', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='minimum_event_duration_minutes',
            field=models.IntegerField(blank=True, help_text='Minimum event duration in minutes. Example: 90', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='must_leave_by',
            field=models.TimeField(blank=True, help_text='Latest time the club must be off-site.', null=True),
        ),
    ]
