# Generated by Django 6.0.5 on 2026-06-08 08:34

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0019_partner_maximum_event_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='preferred_contact_method',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='preferred_months',
        ),
        migrations.AddField(
            model_name='partner',
            name='allowed_months',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=26),
        ),
        migrations.AddField(
            model_name='partner',
            name='allowed_weekday_occurrences',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth'), ('LAST', 'Last')], max_length=14),
        ),
        migrations.AlterField(
            model_name='partner',
            name='allowed_weekdays',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=13),
        ),
        migrations.AlterField(
            model_name='partner',
            name='scheduling_type',
            field=models.CharField(choices=[('DARKEST', 'Darkest Moon'), ('SPRING_FALL', 'Spring/Fall'), ('REQUESTS_MOON', 'Requests some Moon'), ('NO_PREFERENCE', 'No Preference'), ('CUSTOM', 'Custom Rule')], default='DARKEST', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.UniqueConstraint(fields=('partner_type', 'scheduling_type', 'priority'), name='unique_partner_type_scheduling_type_priority'),
        ),
    ]
