# Generated by Django 6.0.5 on 2026-06-08 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0020_remove_partner_event_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run_scheduler', models.BooleanField(default=False, help_text='Check this and save to generate suggested events for this date range.')),
            ],
        ),
        migrations.AlterField(
            model_name='partner',
            name='scheduling_type',
            field=models.CharField(choices=[('DARKEST', 'Darkest Moon'), ('REQUESTS_MOON', 'Requests some Moon'), ('NO_PREFERENCE', 'No Preference'), ('CUSTOM', 'Custom Rule')], default='DARKEST', max_length=30),
        ),
        migrations.CreateModel(
            name='SuggestedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_date', models.DateField()),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUGGESTED', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_events', to='outreach.partner')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('partner', 'suggested_date'), name='unique_partner_suggested_date')],
            },
        ),
    ]
