# Generated by Django 6.0.5 on 2026-06-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0021_schedulerrun_alter_partner_scheduling_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedevent',
            name='manual_entry',
            field=models.BooleanField(default=False, help_text='Check if this suggestion was manually entered and should be preserved.'),
        ),
    ]
