# Generated by Django 6.0.5 on 2026-06-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0022_suggestedevent_manual_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestedevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestedevent',
            name='sunset_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
