# Generated by Django 6.0.5 on 2026-06-08 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0023_suggestedevent_end_time_suggestedevent_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedevent',
            name='scheduler_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_events', to='outreach.schedulerrun'),
        ),
    ]
