# Generated by Django 6.0.5 on 2026-06-08 22:45

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0024_suggestedevent_scheduler_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronomicaltarget',
            name='best_months',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], help_text='Leave blank if this target is useful year-round.', max_length=26),
        ),
    ]
