# Generated by Django 6.0.5 on 2026-06-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0025_alter_astronomicaltarget_best_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='astronomicaltarget',
            name='dec_degrees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='astronomicaltarget',
            name='ra_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
