# Generated by Django 6.0.5 on 2026-06-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0026_astronomicaltarget_dec_degrees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtarget',
            name='altitude_degrees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventtarget',
            name='azimuth_degrees',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
