# Generated by Django 6.0.5 on 2026-06-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0027_eventtarget_altitude_degrees_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventtarget',
            constraint=models.UniqueConstraint(fields=('event', 'target'), name='unique_event_target'),
        ),
    ]
