# Generated by Django 6.0.5 on 2026-06-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0028_eventtarget_unique_event_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtarget',
            name='visible_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventtarget',
            name='visible_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
