# Generated by Django 6.0.5 on 2026-06-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0029_eventtarget_visible_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='auto_bortle_class',
            field=models.FloatField(blank=True, editable=False, help_text='Estimated Bortle class based on sky brightness.', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='sky_brightness_sqm',
            field=models.FloatField(blank=True, editable=False, help_text='Estimated sky brightness in mag/arcsec².', null=True),
        ),
    ]
