# Generated by Django 6.0.5 on 2026-06-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0030_partner_auto_bortle_class_partner_sky_brightness_sqm'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledevent',
            name='weather_cloud_cover_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='weather_last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='weather_precipitation_probability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='weather_summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='weather_temperature_f',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='weather_thunderstorm_probability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='weather_warning_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='weather_watch_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='weather_wind_speed_mph',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
