# Generated by Django 6.0.5 on 2026-06-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0031_scheduledevent_weather_cloud_cover_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledevent',
            name='weather_thunderstorm_probability',
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='weather_heat_index_f',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='weather_rain_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='weather_thunder_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
