# Generated by Django 6.0.5 on 2026-06-15 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0032_remove_scheduledevent_weather_thunderstorm_probability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('days_before_event', models.IntegerField(blank=True, help_text='Example: 10 means due 10 days before the event.', null=True)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('DONE', 'Completed'), ('NA', 'Not Applicable')], default='TODO', max_length=20)),
                ('cancellation_item', models.BooleanField(default=False, help_text='Checked if this item was added because the event was cancelled.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='outreach.scheduledevent')),
            ],
            options={
                'ordering': ['due_date', 'days_before_event', 'title'],
            },
        ),
    ]
