# Generated by Django 6.0.5 on 2026-06-15 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0033_eventchecklistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventChecklist',
            fields=[
            ],
            options={
                'verbose_name': 'Event Checklist',
                'verbose_name_plural': 'Event Checklists',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('outreach.scheduledevent',),
        ),
    ]
