# Generated by Django 6.0.5 on 2026-06-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0034_eventchecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='outreach_committee',
            field=models.BooleanField(default=False, help_text='Member of the AAS Outreach Committee'),
        ),
    ]
