# Generated by Django 6.0.5 on 2026-06-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0035_volunteer_outreach_committee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='sky_brightness_sqm',
            field=models.FloatField(blank=True, help_text='Estimated sky brightness in mag/arcsec².', null=True),
        ),
    ]
