# Generated by Django 6.0.5 on 2026-06-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0037_volunteer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='volunteer_name',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
