# Generated by Django 6.0.5 on 2026-07-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0038_remove_volunteer_volunteer_name_volunteer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='astronomicaltarget',
            name='representative_point',
            field=models.CharField(blank=True, help_text='What these coordinates represent.', max_length=100),
        ),
    ]
