# Generated by Django 6.0.5 on 2026-07-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0039_astronomicaltarget_representative_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledevent',
            name='event_specific_instructions',
            field=models.TextField(blank=True, help_text='Special instructions for this event only. Use the Partner record for recurring location instructions.'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='meeting_location',
            field=models.CharField(blank=True, help_text='Where volunteers should meet upon arrival.', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='parking_instructions',
            field=models.TextField(blank=True, help_text='Recurring parking instructions for this partner/location.'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='setup_location_notes',
            field=models.TextField(blank=True, help_text='Recurring setup notes, such as where telescopes, tables, or check-in should go.'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_arrival_instructions',
            field=models.TextField(blank=True, help_text='Recurring arrival instructions for volunteers at this partner/location.'),
        ),
    ]
