# Generated by Django 6.0.5 on 2026-07-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0040_scheduledevent_event_specific_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='meeting_location',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='parking_instructions',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='setup_location_notes',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='volunteer_arrival_instructions',
        ),
        migrations.AddField(
            model_name='partner',
            name='meeting_location',
            field=models.CharField(blank=True, help_text='Where volunteers should meet upon arrival.', max_length=200),
        ),
        migrations.AddField(
            model_name='partner',
            name='parking_instructions',
            field=models.TextField(blank=True, help_text='Recurring parking instructions for this partner/location.'),
        ),
        migrations.AddField(
            model_name='partner',
            name='setup_location_notes',
            field=models.TextField(blank=True, help_text='Recurring setup notes, such as where telescopes, tables, or check-in should go.'),
        ),
        migrations.AddField(
            model_name='partner',
            name='volunteer_arrival_instructions',
            field=models.TextField(blank=True, help_text='Recurring arrival instructions for volunteers at this partner/location.'),
        ),
    ]
