# Generated by Django 6.0.5 on 2026-07-14 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0041_remove_volunteer_meeting_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingOutlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('COMMUNITY_CALENDAR', 'Community Calendar'), ('NEWS_MEDIA', 'News or Media'), ('SOCIAL_MEDIA', 'Social Media'), ('LIBRARY', 'Library'), ('SCHOOL', 'School or Education'), ('PARKS_OUTDOORS', 'Parks or Outdoors'), ('SCIENCE', 'Science Organization'), ('FAMILY', 'Family Activities'), ('TOURISM', 'Tourism'), ('PARTNER', 'Partner Organization'), ('OTHER', 'Other')], default='COMMUNITY_CALENDAR', max_length=30)),
                ('submission_method', models.CharField(choices=[('API', 'Fully Automated / API'), ('BROWSER', 'Browser Assisted'), ('EMAIL', 'Email'), ('MANUAL_FORM', 'Manual Web Form'), ('SOCIAL', 'Manual Social Media Post'), ('PHONE', 'Phone'), ('OTHER', 'Other')], default='MANUAL_FORM', max_length=30)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Normal'), (4, 'Low')], default=3)),
                ('website_url', models.URLField(blank=True)),
                ('submission_url', models.URLField(blank=True, help_text='Direct link to the event submission page, when available.')),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, default='Texas', max_length=50)),
                ('service_radius_miles', models.PositiveIntegerField(blank=True, help_text="Approximate distance from the outlet's city that it covers. Leave blank for outlets that are not geographically limited.", null=True)),
                ('minimum_lead_days', models.PositiveIntegerField(default=0, help_text='Minimum number of days before an event that it should be submitted.')),
                ('preferred_lead_days', models.PositiveIntegerField(blank=True, help_text='Preferred number of days before an event for submission.', null=True)),
                ('accepts_star_parties', models.BooleanField(default=True)),
                ('accepts_solar_outreach', models.BooleanField(default=True)),
                ('accepts_library_programs', models.BooleanField(default=True)),
                ('accepts_sidewalk_astronomy', models.BooleanField(default=True)),
                ('accepts_custom_events', models.BooleanField(default=True)),
                ('requires_account', models.BooleanField(default=False)),
                ('requires_image', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('submission_instructions', models.TextField(blank=True, help_text='Instructions for submitting an event to this outlet.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advertising Outlet',
                'verbose_name_plural': 'Advertising Outlets',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('last_regenerated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertising_campaign', to='outreach.scheduledevent')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_advertising_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advertising Campaign',
                'verbose_name_plural': 'Advertising Campaigns',
                'ordering': ['event__event_date', 'event__event_name'],
            },
        ),
        migrations.CreateModel(
            name='EventAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('READY', 'Ready to Submit'), ('SUBMITTED', 'Submitted'), ('WAITING_APPROVAL', 'Waiting for Approval'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped'), ('NOT_APPLICABLE', 'Not Applicable'), ('MISSED_DEADLINE', 'Missed Deadline'), ('EXPIRED', 'Expired')], default='NOT_STARTED', max_length=30)),
                ('submission_deadline', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_url', models.URLField(blank=True)),
                ('external_reference', models.CharField(blank=True, help_text='Confirmation number, post ID, or other external reference.', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='outreach.advertisingcampaign')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_advertisements', to='outreach.advertisingoutlet')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_event_advertisements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Advertisement',
                'verbose_name_plural': 'Event Advertisements',
                'ordering': ['submission_deadline', 'outlet__priority', 'outlet__name'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'outlet'), name='unique_campaign_advertising_outlet')],
            },
        ),
    ]
