# Generated by Django 6.0.5 on 2026-07-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0042_advertisingoutlet_advertisingcampaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisingcampaign',
            name='advertising_radius_miles',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='advertisingcampaign',
            name='use_full_service_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisingoutlet',
            name='covers_full_service_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisingoutlet',
            name='estimated_submission_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
