# Generated by Django 6.0.5 on 2026-07-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0043_advertisingcampaign_advertising_radius_miles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisingcampaign',
            name='advertising_radius_miles',
        ),
        migrations.RemoveField(
            model_name='advertisingcampaign',
            name='use_full_service_area',
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='advertising_radius_miles',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='use_full_service_area',
            field=models.BooleanField(default=False),
        ),
    ]
