# Generated by Django 6.0.5 on 2026-07-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0044_remove_advertisingcampaign_advertising_radius_miles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledevent',
            old_name='use_full_service_area',
            new_name='advertise_to_full_service_area',
        ),
    ]
