# Generated by Django 6.0.5 on 2026-07-18 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0045_rename_use_full_service_area_scheduledevent_advertise_to_full_service_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingPlaybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='Internal description of when this playbook should be used.')),
                ('short_description_template', models.TextField(blank=True, help_text='Short promotional description. Available placeholders include {event_name}, {event_date}, {start_time}, {end_time}, {location_name}, {city}, and {partner_name}.')),
                ('long_description_template', models.TextField(blank=True, help_text='Long-form event description for calendars and websites.')),
                ('facebook_template', models.TextField(blank=True, help_text='Suggested Facebook post.')),
                ('newsletter_template', models.TextField(blank=True, help_text='Suggested newsletter copy.')),
                ('community_calendar_template', models.TextField(blank=True, help_text='Suggested community-calendar listing.')),
                ('email_template', models.TextField(blank=True, help_text='Suggested email announcement.')),
                ('image_guidance', models.TextField(blank=True, help_text='Instructions or recommendations for the image that should accompany this campaign.')),
                ('automation_notes', models.TextField(blank=True, help_text='Reusable notes for future browser-assisted submission automation.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advertising Playbook',
                'verbose_name_plural': 'Advertising Playbooks',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='advertisingcampaign',
            name='advertising_title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='advertisingcampaign',
            name='community_calendar_copy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='advertisingcampaign',
            name='copy_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisingcampaign',
            name='email_copy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='advertisingcampaign',
            name='facebook_copy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='advertisingcampaign',
            name='image_guidance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='advertisingcampaign',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='advertisingcampaign',
            name='newsletter_copy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='advertisingcampaign',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='advertisingcampaign',
            name='playbook',
            field=models.ForeignKey(blank=True, help_text='Optional reusable copy and submission guidance for this campaign.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='outreach.advertisingplaybook'),
        ),
    ]
