# Generated by Django 6.0.5 on 2026-07-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0046_advertisingplaybook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisingplaybook',
            name='avoid_language',
            field=models.TextField(blank=True, help_text='Words, phrases, or topics that should be avoided.'),
        ),
        migrations.AddField(
            model_name='advertisingplaybook',
            name='generate_calendar_copy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advertisingplaybook',
            name='generate_email_copy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advertisingplaybook',
            name='generate_facebook_copy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advertisingplaybook',
            name='generate_newsletter_copy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advertisingplaybook',
            name='key_messages',
            field=models.TextField(blank=True, help_text='Important ideas that should always appear in generated advertising.'),
        ),
        migrations.AddField(
            model_name='advertisingplaybook',
            name='target_audience',
            field=models.CharField(blank=True, help_text='Example: Families, beginners, campers, scouts, or the general public.', max_length=200),
        ),
        migrations.AddField(
            model_name='advertisingplaybook',
            name='voice',
            field=models.CharField(blank=True, help_text='Example: Friendly, educational, welcoming, beginner-focused.', max_length=150),
        ),
        migrations.AlterField(
            model_name='advertisingplaybook',
            name='automation_notes',
            field=models.TextField(blank=True, help_text='Internal notes used later for browser-assisted advertising.'),
        ),
        migrations.AlterField(
            model_name='advertisingplaybook',
            name='community_calendar_template',
            field=models.TextField(blank=True, help_text='Optional community calendar template.'),
        ),
        migrations.AlterField(
            model_name='advertisingplaybook',
            name='email_template',
            field=models.TextField(blank=True, help_text='Optional email announcement template.'),
        ),
        migrations.AlterField(
            model_name='advertisingplaybook',
            name='facebook_template',
            field=models.TextField(blank=True, help_text='Optional Facebook-specific template.'),
        ),
        migrations.AlterField(
            model_name='advertisingplaybook',
            name='image_guidance',
            field=models.TextField(blank=True, help_text='Recommended style of image to accompany advertisements.'),
        ),
        migrations.AlterField(
            model_name='advertisingplaybook',
            name='long_description_template',
            field=models.TextField(blank=True, help_text='Optional long-form advertising template.'),
        ),
        migrations.AlterField(
            model_name='advertisingplaybook',
            name='newsletter_template',
            field=models.TextField(blank=True, help_text='Optional newsletter template.'),
        ),
        migrations.AlterField(
            model_name='advertisingplaybook',
            name='short_description_template',
            field=models.TextField(blank=True, help_text='Optional short promotional template. Available placeholders include:\n{event_name}\n{event_date}\n{start_time}\n{end_time}\n{location_name}\n{partner_name}\n{city}'),
        ),
    ]
