# Generated by Django 6.0.5 on 2026-07-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0047_advertisingplaybook_avoid_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisingplaybook',
            name='automation_notes',
            field=models.TextField(blank=True, help_text='Internal notes used by browser-assisted advertising automation.'),
        ),
        migrations.AlterField(
            model_name='advertisingplaybook',
            name='image_guidance',
            field=models.TextField(blank=True, help_text='Suggested image style or subject to accompany generated advertisements.'),
        ),
        migrations.AlterField(
            model_name='advertisingplaybook',
            name='short_description_template',
            field=models.TextField(blank=True, help_text='Optional short promotional template.\n\nAvailable placeholders:\n{event_name}\n{event_date}\n{start_time}\n{end_time}\n{location_name}\n{partner_name}\n{city}'),
        ),
        migrations.AlterField(
            model_name='advertisingplaybook',
            name='target_audience',
            field=models.CharField(choices=[('GENERAL_PUBLIC', 'General Public'), ('FAMILIES', 'Families'), ('BEGINNERS', 'Beginners'), ('STUDENTS', 'Students'), ('SCOUTS', 'Scouts'), ('CAMPERS', 'Campers'), ('EDUCATORS', 'Educators'), ('ASTRONOMERS', 'Experienced Astronomers')], default='GENERAL_PUBLIC', help_text='Primary audience this advertising is intended for.', max_length=25),
        ),
        migrations.AlterField(
            model_name='advertisingplaybook',
            name='voice',
            field=models.CharField(choices=[('FRIENDLY', 'Friendly'), ('EDUCATIONAL', 'Educational'), ('PROFESSIONAL', 'Professional'), ('EXCITING', 'Exciting'), ('FORMAL', 'Formal')], default='FRIENDLY', help_text='Overall tone used when generating advertising copy.', max_length=20),
        ),
    ]
