# Generated by Django 6.0.5 on 2026-07-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0048_alter_advertisingplaybook_automation_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisingoutlet',
            name='allows_emojis',
            field=models.BooleanField(default=False, help_text='Whether emojis are appropriate for this outlet.'),
        ),
        migrations.AddField(
            model_name='advertisingoutlet',
            name='allows_hashtags',
            field=models.BooleanField(default=False, help_text='Whether hashtags are appropriate for this outlet.'),
        ),
        migrations.AddField(
            model_name='advertisingoutlet',
            name='allows_html',
            field=models.BooleanField(default=False, help_text='Whether the description field accepts HTML formatting.'),
        ),
        migrations.AddField(
            model_name='advertisingoutlet',
            name='allows_images',
            field=models.BooleanField(default=True, help_text='Whether the outlet allows an image to be submitted.'),
        ),
        migrations.AddField(
            model_name='advertisingoutlet',
            name='allows_links',
            field=models.BooleanField(default=True, help_text='Whether links may be included in the submitted copy.'),
        ),
        migrations.AddField(
            model_name='advertisingoutlet',
            name='content_guidance',
            field=models.TextField(blank=True, help_text='Outlet-specific writing rules, required details, tone, formatting guidance, or prohibited content.'),
        ),
        migrations.AddField(
            model_name='advertisingoutlet',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, help_text='The last date and time the submission instructions were verified.', null=True),
        ),
        migrations.AddField(
            model_name='advertisingoutlet',
            name='maximum_description_characters',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of characters allowed in the event description. Leave blank when there is no known limit.', null=True),
        ),
        migrations.AddField(
            model_name='advertisingoutlet',
            name='maximum_title_characters',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of characters allowed in the event title. Leave blank when there is no known limit.', null=True),
        ),
        migrations.AddField(
            model_name='advertisingoutlet',
            name='requires_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advertisingoutlet',
            name='requires_captcha',
            field=models.BooleanField(default=False, help_text='Whether the submission form normally requires manual CAPTCHA completion.'),
        ),
        migrations.AddField(
            model_name='advertisingoutlet',
            name='requires_contact_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisingoutlet',
            name='requires_contact_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisingoutlet',
            name='requires_cost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisingoutlet',
            name='requires_description',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advertisingoutlet',
            name='requires_end_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisingoutlet',
            name='requires_event_title',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advertisingoutlet',
            name='requires_plain_text',
            field=models.BooleanField(default=True, help_text='Whether submitted copy should be plain text only.'),
        ),
        migrations.AddField(
            model_name='advertisingoutlet',
            name='requires_registration_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisingoutlet',
            name='requires_start_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advertisingoutlet',
            name='verification_notes',
            field=models.TextField(blank=True, help_text="Notes about the latest review of this outlet's submission process."),
        ),
    ]
