# Generated by Django 6.0.5 on 2026-07-18 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0049_advertisingoutlet_allows_emojis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventadvertisement',
            name='copy_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventadvertisement',
            name='copy_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventadvertisement',
            name='copy_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_event_advertisements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventadvertisement',
            name='generated_description',
            field=models.TextField(blank=True, help_text='Event description prepared specifically for this outlet.'),
        ),
        migrations.AddField(
            model_name='eventadvertisement',
            name='generated_email_body',
            field=models.TextField(blank=True, help_text='Email body prepared for outlets that accept submissions by email.'),
        ),
        migrations.AddField(
            model_name='eventadvertisement',
            name='generated_email_subject',
            field=models.CharField(blank=True, help_text='Email subject prepared for outlets that accept submissions by email.', max_length=500),
        ),
        migrations.AddField(
            model_name='eventadvertisement',
            name='generated_title',
            field=models.CharField(blank=True, help_text='Event title prepared specifically for this outlet.', max_length=500),
        ),
        migrations.AddField(
            model_name='eventadvertisement',
            name='submitted_description',
            field=models.TextField(blank=True, help_text='The final description actually submitted to the outlet.'),
        ),
        migrations.AddField(
            model_name='eventadvertisement',
            name='submitted_email_body',
            field=models.TextField(blank=True, help_text='The final email body actually sent to the outlet.'),
        ),
        migrations.AddField(
            model_name='eventadvertisement',
            name='submitted_email_subject',
            field=models.CharField(blank=True, help_text='The final email subject actually sent to the outlet.', max_length=500),
        ),
        migrations.AddField(
            model_name='eventadvertisement',
            name='submitted_title',
            field=models.CharField(blank=True, help_text='The final title actually submitted to the outlet.', max_length=500),
        ),
    ]
