# Generated by Django 6.0.5 on 2026-08-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0050_eventadvertisement_copy_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvolunteer',
            name='telescope_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of telescopes this volunteer plans to bring.'),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='volunteer_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of volunteers allowed to sign up. Leave blank for unlimited.', null=True),
        ),
        migrations.AlterField(
            model_name='eventvolunteer',
            name='role',
            field=models.CharField(choices=[('TELESCOPE', 'Telescope'), ('SUPPORT', 'Welcome / Junior Astronomy Display/ Telescope Petting Zoo'), ('OTHER', 'Other')], default='TELESCOPE', max_length=20),
        ),
    ]
