# Generated by Django 6.0.5 on 2026-08-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0051_eventvolunteer_telescope_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackoutDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blackout_date', models.DateField(help_text='Date that should not be used by the yearly scheduler.', unique=True)),
                ('reason', models.CharField(help_text='Reason this date is unavailable.', max_length=255)),
                ('active', models.BooleanField(default=True, help_text='Uncheck to allow this date to be scheduled without deleting the blackout record.')),
            ],
            options={
                'verbose_name': 'Blackout Date',
                'verbose_name_plural': 'Blackout Dates',
                'ordering': ('blackout_date',),
            },
        ),
    ]
