# Generated by Django 6.0.5 on 2026-08-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0052_blackoutdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventvolunteer',
            name='telescope_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of telescopes this volunteer plans to bring.', null=True),
        ),
    ]
