# Generated by Django 6.0.5 on 2026-08-19 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0053_alter_eventvolunteer_telescope_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLocationResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='partner_location_resources/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_resources', to='outreach.partner')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
